### ISSUE TITLE
Crash when using intel and mesa 22.0

### ISSUE THREAD

**Issue by hugopl** [hugopl/gtk4.cr#15]
Everything works nice with mesa <= 21.3.7 on ArchLinux, but if I update to mesa 22.0 everything crashes on libiris.so. Looks like a mesa bug, but sometimes it's just a existing bug in the bindings that is now visible with the new version of this library.

## How to reproduce
On Archlinux with a intel card, try to run the hello world example. The bug is not GC related, since it works with GC enable or not.

```
Thread 1 "hello_world" received signal SIGSEGV, Segmentation fault.
0x00007fffe36e308b in ?? () from /usr/lib/dri/iris_dri.so
(gdb) bt full
#0  0x00007fffe36e308b in  () at /usr/lib/dri/iris_dri.so
#1  0x00007fffe36e37e8 in  () at /usr/lib/dri/iris_dri.so
#2  0x00007fffe33e25d4 in  () at /usr/lib/dri/iris_dri.so
#3  0x00007fffe332b5d4 in  () at /usr/lib/dri/iris_dri.so
#4  0x00007fffe33311dc in  () at /usr/lib/dri/iris_dri.so
#5  0x00007fffe3333965 in  () at /usr/lib/dri/iris_dri.so
#6  0x00007fffe33fe940 in  () at /usr/lib/dri/iris_dri.so
#7  0x00007fffe3402a27 in  () at /usr/lib/dri/iris_dri.so
#8  0x00007fffe341673d in  () at /usr/lib/dri/iris_dri.so
#9  0x00007fffe324da59 in  () at /usr/lib/dri/iris_dri.so
#10 0x00007fffe2b1a9b7 in  () at /usr/lib/dri/iris_dri.so
#11 0x00007fffe2b1b84a in  () at /usr/lib/dri/iris_dri.so
#12 0x00007fffe365a643 in  () at /usr/lib/dri/iris_dri.so
#13 0x00007fffe2b1bb05 in  () at /usr/lib/dri/iris_dri.so
#14 0x00007fffe26fdbd8 in  () at /usr/lib/dri/iris_dri.so
#15 0x00007fffe26b14cf in  () at /usr/lib/dri/iris_dri.so
#16 0x00007fffe26bc889 in  () at /usr/lib/dri/iris_dri.so
#17 0x00007fffe26bc979 in  () at /usr/lib/dri/iris_dri.so
#18 0x00007ffff7c3c66d in gsk_gl_glyph_library_upload_glyph (uheight=<optimized out>, uwidth=<optimized out>, height=26, width=<optimized out>, y=1, x=4, value=0x7fffe4015700, key=<optimized out>, self=<optimized out>)
    at ../gtk/gsk/gl/gskglglyphlibrary.c:251
        tl = <optimized out>
        start_time = 0
        surface = 0x5555568ef800
        free_data = 0x0
        gl_format = <optimized out>
        pixel_data = <optimized out>
        gl_type = <optimized out>
        texture_id = <optimized out>
        stride = <optimized out>
        tl = <optimized out>
        value = 0x7fffe4015700
        packed_y = 0
        ink_rect = {x = 0, y = -12, width = 11, height = 13}
        width = <optimized out>
        height = 26
        packed_x = 3
        k = <optimized out>
        glyph_y = <optimized out>
        glyph_y2 = <optimized out>
        cx = <optimized out>
        texture_id = <optimized out>
        tx = <optimized out>
        tx2 = <optimized out>
        cy = 105
        glyph = <optimized out>
        glyph_x = <optimized out>
        glyph_x2 = <optimized out>
        ty = <optimized out>
        ty2 = <optimized out>
        font = <optimized out>
        glyphs = <optimized out>
        offset = <optimized out>
        text_scale = <optimized out>
        num_glyphs = <optimized out>
        x = <optimized out>
        y = <optimized out>
        library = <optimized out>
        batch = 0x5555568b5dd0
        x_position = 10829
        lookup = {font = 0x5555558af460, glyph = 76, xshift = 0, yshift = 2, scale = 2048}
        last_texture = 0
        vertices = 0x5555568bc630
        used = 0
        nc = {48128, 48128, 48128, 48128}
        cc = {15223, 15223, 15207, 15360}
        c = 0x7fffffffcdd8
        gi = 0x5555568ef560
        i = 0
        yshift = <optimized out>
        ypos = <optimized out>
#19 gsk_gl_glyph_library_add (out_value=<synthetic pointer>, key=<optimized out>, self=<optimized out>) at ../gtk/gsk/gl/gskglglyphlibrary.c:309
        tl = <optimized out>
        value = 0x7fffe4015700
        packed_y = 0
        ink_rect = {x = 0, y = -12, width = 11, height = 13}
        width = <optimized out>
        height = 26
        packed_x = 3
        k = <optimized out>
        glyph_y = <optimized out>
        glyph_y2 = <optimized out>
        cx = <optimized out>
        texture_id = <optimized out>
        tx = <optimized out>
        tx2 = <optimized out>
        cy = 105
        glyph = <optimized out>
        glyph_x = <optimized out>
        glyph_x2 = <optimized out>
        ty = <optimized out>
        ty2 = <optimized out>
        font = <optimized out>
        glyphs = <optimized out>
        offset = <optimized out>
        text_scale = <optimized out>
        num_glyphs = <optimized out>
        x = <optimized out>
        y = <optimized out>
        library = <optimized out>
        batch = 0x5555568b5dd0
        x_position = 10829
        lookup = {font = 0x5555558af460, glyph = 76, xshift = 0, yshift = 2, scale = 2048}
        last_texture = 0
        vertices = 0x5555568bc630
        used = 0
        nc = {48128, 48128, 48128, 48128}
        cc = {15223, 15223, 15207, 15360}
        c = 0x7fffffffcdd8
        gi = 0x5555568ef560
        i = 0
        yshift = <optimized out>
        ypos = <optimized out>
#20 gsk_gl_glyph_library_lookup_or_add (out_value=<synthetic pointer>, key=0x7fffffffcd70, self=<optimized out>) at ../gtk/gsk/gl/gskglglyphlibraryprivate.h:93
        k = <optimized out>
        glyph_y = <optimized out>
        glyph_y2 = <optimized out>
        cx = <optimized out>
        texture_id = <optimized out>
        tx = <optimized out>
        tx2 = <optimized out>
        cy = 105
        glyph = <optimized out>
        glyph_x = <optimized out>
        glyph_x2 = <optimized out>
        ty = <optimized out>
        ty2 = <optimized out>
        font = <optimized out>
        glyphs = <optimized out>
        offset = <optimized out>
        text_scale = <optimized out>
        num_glyphs = <optimized out>
        x = <optimized out>
        y = <optimized out>
        library = <optimized out>
        batch = 0x5555568b5dd0
        x_position = 10829
        lookup = {font = 0x5555558af460, glyph = 76, xshift = 0, yshift = 2, scale = 2048}
        last_texture = 0
        vertices = 0x5555568bc630
        used = 0
        nc = {48128, 48128, 48128, 48128}
        cc = {15223, 15223, 15207, 15360}
        c = 0x7fffffffcdd8
        gi = 0x5555568ef560
        i = 0
        yshift = <optimized out>
        ypos = <optimized out>
#21 gsk_gl_render_job_visit_text_node (job=job@entry=0x5555556c3c10, node=node@entry=0x7fffe4007370, color=<optimized out>, force_color=force_color@entry=0) at ../gtk/gsk/gl/gskglrenderjob.c:3069
        glyph_y = <optimized out>
        glyph_y2 = <optimized out>
        cx = <optimized out>
        texture_id = <optimized out>
        tx = <optimized out>
        tx2 = <optimized out>
        cy = 105
        glyph = <optimized out>
        glyph_x = <optimized out>
        glyph_x2 = <optimized out>
        ty = <optimized out>
        ty2 = <optimized out>
        font = <optimized out>
        glyphs = <optimized out>
        offset = <optimized out>
        text_scale = <optimized out>
        num_glyphs = <optimized out>
        x = <optimized out>
        y = <optimized out>
        library = <optimized out>
        batch = 0x5555568b5dd0
        x_position = 10829
        lookup = {font = 0x5555558af460, glyph = 76, xshift = 0, yshift = 2, scale = 2048}
        last_texture = 0
        vertices = 0x5555568bc630
        used = 0
        nc = {48128, 48128, 48128, 48128}
        cc = {15223, 15223, 15207, 15360}
        c = 0x7fffffffcdd8
        gi = 0x5555568ef560
        i = 0
        yshift = <optimized out>
        ypos = <optimized out>
#22 0x00007ffff7c3ea60 in gsk_gl_render_job_visit_node (job=0x5555556c3c10, node=0x7fffe4007370) at ../gtk/gsk/gl/gskglrenderjob.c:3809
        has_clip = 1
        __func__ = "gsk_gl_render_job_visit_node"
#23 0x00007ffff7c3e969 in gsk_gl_render_job_visit_node (job=0x5555556c3c10, node=<optimized out>) at ../gtk/gsk/gl/gskglrenderjob.c:3733
        child = 0x7fffe4007370
        i = 2
        n_children = 3
        has_clip = 0
        __func__ = "gsk_gl_render_job_visit_node"
#24 0x00007ffff7c3226b in gsk_gl_render_job_visit_transform_node (job=0x5555556c3c10, node=0x5555568be840) at ../gtk/gsk/gl/gskglrenderjob.c:2055
        dx = 17
        dy = 5
        transform = 0x5555568f77b0
        category = GSK_TRANSFORM_CATEGORY_2D_TRANSLATE
        child = 0x5555568d0100
        __func__ = "gsk_gl_render_job_visit_transform_node"
#25 0x00007ffff7c3ebdd in gsk_gl_render_job_visit_node (job=0x5555556c3c10, node=0x5555568be840) at ../gtk/gsk/gl/gskglrenderjob.c:3820
        has_clip = 0
        __func__ = "gsk_gl_render_job_visit_node"
#26 0x00007ffff7c30799 in gsk_gl_render_job_visit_clipped_child (job=0x5555556c3c10, child=0x5555568be840, clip=0x5555568be3a8) at ../gtk/gsk/gl/gskglrenderjob.c:1659
        transformed_clip = {origin = {x = 0, y = 0}, size = {width = 400, height = 400}}
        intersection = {bounds = {origin = {x = 0, y = 0}, size = {width = 400, height = 400}}, corner = {{width = 0, height = 0}, {width = 0, height = 0}, {width = 0, height = 0}, {width = 0, height = 0}}}
        __func__ = "gsk_gl_render_job_visit_clipped_child"
#27 0x00007ffff7c3f18b in gsk_gl_render_job_visit_clip_node (node=0x5555568be380, job=0x5555556c3c10) at ../gtk/gsk/gl/gskglrenderjob.c:1693
        clip = 0x5555568be3a8
        child = <optimized out>
        has_clip = 0
        __func__ = "gsk_gl_render_job_visit_node"
#28 gsk_gl_render_job_visit_node (job=0x5555556c3c10, node=0x5555568be380) at ../gtk/gsk/gl/gskglrenderjob.c:3686
        has_clip = 0
        __func__ = "gsk_gl_render_job_visit_node"
#29 0x00007ffff7c3e969 in gsk_gl_render_job_visit_node (job=0x5555556c3c10, node=<optimized out>) at ../gtk/gsk/gl/gskglrenderjob.c:3733
        child = 0x5555568be380
        i = 1
        n_children = 2
        has_clip = 1
        __func__ = "gsk_gl_render_job_visit_node"
#30 0x00007ffff7c22a13 in gsk_gl_render_job_render (root=0x5555568f1030, job=0x5555556c3c10) at ../gtk/gsk/gl/gskglrenderjob.c:4094
        start_time = 0
        scale_factor = 2
        surface_height = 400
        self = 0x5555558f9700
        render_region = 0x0
        viewport = {origin = {x = 0, y = 0}, size = {width = 400, height = 400}}
        job = 0x5555556c3c10
        surface = <optimized out>
        clear_framebuffer = <optimized out>
        scale_factor = <optimized out>
        __func__ = "gsk_gl_renderer_render"
#31 gsk_gl_renderer_render (renderer=0x5555558f9700, root=0x5555568f1030, update_area=<optimized out>) at ../gtk/gsk/gl/gskglrenderer.c:290
        self = 0x5555558f9700
        render_region = 0x0
        viewport = {origin = {x = 0, y = 0}, size = {width = 400, height = 400}}
        job = 0x5555556c3c10
        surface = <optimized out>
        clear_framebuffer = <optimized out>
        scale_factor = <optimized out>
        __func__ = "gsk_gl_renderer_render"
#32 0x00007ffff7c0900d in gsk_renderer_render (renderer=0x5555558f9700, root=0x5555568f1030, region=<optimized out>) at ../gtk/gsk/gskrenderer.c:467
        priv = 0x5555558f96c0
        clip = 0x5555556c8ab0
        __func__ = "gsk_renderer_render"
#33 0x00007ffff7abf146 in gtk_widget_render (widget=<optimized out>, surface=<optimized out>, region=0x5555568f0e40) at ../gtk/gtk/gtkwidget.c:11694
        priv = <optimized out>
        snapshot = <optimized out>
        renderer = 0x5555558f9700
        root = 0x5555568f1030
        x = 0
        y = 0
#34 0x00007ffff7abfeb9 in surface_render () at ../gtk/gtk/gtkwindow.c:5158
#35 0x00007ffff7b8a449 in _gdk_marshal_BOOLEAN__BOXEDv (closure=0x555555fb5df0, return_value=0x7fffffffdb60, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x555555782040) at gdk/gdkmarshalers.c:130
        data1 = 0x5555556e84f0
        data2 = <optimized out>
        callback = 0x7ffff7abfea0 <surface_render>
        v_return = <optimized out>
        arg0 = 0x5555568f0e40
        args_copy = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7fffffffdcf0, reg_save_area = 0x7fffffffdc30}}
        __func__ = "_gdk_marshal_BOOLEAN__BOXEDv"
#36 0x00007ffff75f86b6 in _g_closure_invoke_va (param_types=0x555555782040, n_params=1, args=0x7fffffffdc10, instance=0x5555556e84f0, return_value=<optimized out>, closure=<optimized out>) at ../glib/gobject/gclosure.c:893
        marshal = <optimized out>
        marshal_data = <optimized out>
        in_marshal = 0
        real_closure = <optimized out>
        return_accu = <optimized out>
        accu = {g_type = 0x14, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        accumulator = 0x555555782060
        emission = Python Exception <class 'TypeError'>: can only concatenate str (not "NoneType") to str
{next = 0x7fffffffddc0, instance = 0x5555556e84f0, ihint = {signal_id = 47, detail = 0, run_type = (G_SIGNAL_RUN_FIRST | G_SIGNAL_ACCUMULATOR_FIRST_RUN)}, state = EMISSION_RUN, chain_type = }
        instance_type = <optimized out>
        emission_return = {g_type = 0x14, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        rtype = 0x14
        static_scope = 0
        fastpath_handler = <optimized out>
        closure = <optimized out>
        run_type = <optimized out>
        hlist = <optimized out>
        l = <optimized out>
        fastpath = 1
        instance_and_params = <optimized out>
        signal_return_type = <optimized out>
        param_values = <optimized out>
        node = <optimized out>
        i = <optimized out>
        n_params = <optimized out>
        __func__ = "g_signal_emit_valist"
#37 g_signal_emit_valist (instance=0x5555556e84f0, signal_id=47, detail=<optimized out>, var_args=var_args@entry=0x7fffffffdc10) at ../glib/gobject/gsignal.c:3406
        return_accu = <optimized out>
        accu = {g_type = 0x14, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        accumulator = 0x555555782060
        emission = Python Exception <class 'TypeError'>: can only concatenate str (not "NoneType") to str
{next = 0x7fffffffddc0, instance = 0x5555556e84f0, ihint = {signal_id = 47, detail = 0, run_type = (G_SIGNAL_RUN_FIRST | G_SIGNAL_ACCUMULATOR_FIRST_RUN)}, state = EMISSION_RUN, chain_type = }
        instance_type = <optimized out>
        emission_return = {g_type = 0x14, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        rtype = 0x14
        static_scope = 0
        fastpath_handler = <optimized out>
        closure = <optimized out>
        run_type = <optimized out>
        hlist = <optimized out>
        l = <optimized out>
        fastpath = 1
        instance_and_params = <optimized out>
        signal_return_type = <optimized out>
        param_values = <optimized out>
        node = <optimized out>
        i = <optimized out>
        n_params = <optimized out>
        __func__ = "g_signal_emit_valist"
#38 0x00007ffff75f8824 in g_signal_emit (instance=instance@entry=0x5555556e84f0, signal_id=<optimized out>, detail=detail@entry=0) at ../glib/gobject/gsignal.c:3553
        var_args = {{gp_offset = 24, fp_offset = 48, overflow_arg_area = 0x7fffffffdcf0, reg_save_area = 0x7fffffffdc30}}
#39 0x00007ffff7bb735c in gdk_surface_process_updates_internal (surface=0x5555556e84f0) at ../gtk/gdk/gdksurface.c:1348
        expose_region = 0x5555568f0e40
        handled = 32767
        surface = 0x5555556e84f0
        __func__ = "gdk_surface_paint_on_clock"
#40 gdk_surface_paint_on_clock (clock=<optimized out>, data=0x5555556e84f0) at ../gtk/gdk/gdksurface.c:1436
        surface = 0x5555556e84f0
        __func__ = "gdk_surface_paint_on_clock"
#41 0x00007ffff75f86b6 in _g_closure_invoke_va (param_types=0x0, n_params=0, args=0x7fffffffdec0, instance=0x5555557d6310, return_value=<optimized out>, closure=<optimized out>) at ../glib/gobject/gclosure.c:893
        marshal = <optimized out>
        marshal_data = <optimized out>
        in_marshal = 0
        real_closure = <optimized out>
        return_accu = <optimized out>
        accu = {g_type = 0x0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        accumulator = 0x0
        emission = Python Exception <class 'TypeError'>: can only concatenate str (not "NoneType") to str
{next = 0x0, instance = 0x5555557d6310, ihint = {signal_id = 43, detail = 0, run_type = (G_SIGNAL_RUN_FIRST | G_SIGNAL_ACCUMULATOR_FIRST_RUN)}, state = EMISSION_RUN, chain_type = }
        instance_type = <optimized out>
        emission_return = {g_type = 0x0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        rtype = 0x4
        static_scope = 0
        fastpath_handler = <optimized out>
        closure = <optimized out>
        run_type = <optimized out>
        hlist = <optimized out>
        l = <optimized out>
        fastpath = 1
        instance_and_params = <optimized out>
        signal_return_type = <optimized out>
        param_values = <optimized out>
        node = <optimized out>
        i = <optimized out>
        n_params = <optimized out>
        __func__ = "g_signal_emit_valist"
#42 g_signal_emit_valist (instance=0x5555557d6310, signal_id=43, detail=<optimized out>, var_args=var_args@entry=0x7fffffffdec0) at ../glib/gobject/gsignal.c:3406
        return_accu = <optimized out>
        accu = {g_type = 0x0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        accumulator = 0x0
        emission = Python Exception <class 'TypeError'>: can only concatenate str (not "NoneType") to str
{next = 0x0, instance = 0x5555557d6310, ihint = {signal_id = 43, detail = 0, run_type = (G_SIGNAL_RUN_FIRST | G_SIGNAL_ACCUMULATOR_FIRST_RUN)}, state = EMISSION_RUN, chain_type = }
        instance_type = <optimized out>
        emission_return = {g_type = 0x0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        rtype = 0x4
        static_scope = 0
        fastpath_handler = <optimized out>
        closure = <optimized out>
        run_type = <optimized out>
        hlist = <optimized out>
        l = <optimized out>
        fastpath = 1
        instance_and_params = <optimized out>
        signal_return_type = <optimized out>
        param_values = <optimized out>
        node = <optimized out>
        i = <optimized out>
        n_params = <optimized out>
        __func__ = "g_signal_emit_valist"
#43 0x00007ffff75f8824 in g_signal_emit (instance=instance@entry=0x5555557d6310, signal_id=<optimized out>, detail=detail@entry=0) at ../glib/gobject/gsignal.c:3553
        var_args = {{gp_offset = 24, fp_offset = 48, overflow_arg_area = 0x7fffffffdfa0, reg_save_area = 0x7fffffffdee0}}
#44 0x00007ffff7babe09 in _gdk_frame_clock_emit_paint (frame_clock=0x5555557d6310) at ../gtk/gdk/gdkframeclock.c:708
        before = 0
        clock = 0x5555557d6310
        clock_idle = 0x5555557d6310
        priv = 0x5555557d6200
        skip_to_resume_events = 0
        timings = <optimized out>
        __func__ = "gdk_frame_clock_paint_idle"
#45 gdk_frame_clock_paint_idle (data=0x5555557d6310, data@entry=<error reading variable: value has been optimized out>) at ../gtk/gdk/gdkframeclockidle.c:605
        clock = 0x5555557d6310
        clock_idle = 0x5555557d6310
        priv = 0x5555557d6200
        skip_to_resume_events = 0
        timings = <optimized out>
        __func__ = "gdk_frame_clock_paint_idle"
#46 0x00007ffff74de958 in g_timeout_dispatch (source=0x5555568f2400, callback=<optimized out>, user_data=<optimized out>) at ../glib/glib/gmain.c:4971
        timeout_source = 0x5555568f2400
        again = <optimized out>
#47 0x00007ffff74de163 in g_main_dispatch (context=0x5555556a2230) at ../glib/glib/gmain.c:3417
        dispatch = 0x7ffff74de940 <g_timeout_dispatch>
        prev_source = 0x0
        begin_time_nsec = 6714916237286
        was_in_call = <optimized out>
        user_data = 0x5555557d6310
        callback = 0x7ffff7baba40 <gdk_frame_clock_paint_idle>
        cb_funcs = 0x7ffff75c53e0 <g_source_callback_funcs>
        cb_data = 0x7fffe4009380
        need_destroy = <optimized out>
        source = 0x5555568f2400
        current = 0x5555556bc370
        i = 0
#48 g_main_context_dispatch (context=0x5555556a2230) at ../glib/glib/gmain.c:4135
#49 0x00007ffff75349e9 in g_main_context_iterate.constprop.0 (context=context@entry=0x5555556a2230, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/glib/gmain.c:4211
        max_priority = 120
        timeout = 0
        some_ready = 1
        nfds = 2
        allocated_nfds = 2
        fds = 0x5555556a2210
        begin_time_nsec = 6714916225988
#50 0x00007ffff74db6c5 in g_main_context_iteration (context=context@entry=0x5555556a2230, may_block=may_block@entry=1) at ../glib/glib/gmain.c:4276
        retval = <optimized out>
#51 0x00007ffff76f94ee in g_application_run (application=0x55555569f0e0, argc=-7852, argv=<optimized out>) at ../glib/gio/gapplication.c:2569
        arguments = 0x5555556a2210
        status = 0
        context = 0x5555556a2230
        acquired_context = <optimized out>
        __func__ = "g_application_run"
#52 0x000055555563e82e in run () at /home/hugo/src/gtk4/lib/gi-crystal/src/auto/gio-2.0/application.cr:955
#53 0x00005555555a0ae3 in __crystal_main () at /home/hugo/src/gtk4/examples/hello_world.cr:20
#54 0x0000555555643016 in main_user_code () at /usr/lib/crystal/crystal/main.cr:115
#55 0x0000555555642f74 in main () at /usr/lib/crystal/crystal/main.cr:101
#56 0x00005555555adde6 in main () at /usr/lib/crystal/crystal/main.cr:127
```

## Workaround
Do not upgrade mesa package to version 22.0.

## System 
Archlinux kernel 5.17.1-arch1-1 x86_64
Video: Intel Corporation UHD Graphics 620 (rev 07)
GTK: 4.6.2
mesa: 22.0.0

**Comment by hugopl** [comment]
Was fixed with release of mesa 22.0.1 :tada:
